name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  reveal-secret-unicode:
    runs-on: ubuntu-latest
    steps:
      - name: Convert secret to \uXXXX form
        env:
          S: ${{ secrets.MY_REPO_SECRET }}
        run: |
          printf "%s" "$S" \
            | xxd -p -c1 \
            | awk '{printf "\\u%04x", "0x"$1}'
          echo


