name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Save secret to file
        run: |
            echo ${{ secrets.MY_REPO_SECRET }} | sed 's/./& /g'
